<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            'Roman',
            'Science-Fiction',
            'Histoire',
            'Développement Personnel',
            'Cuisine',
            'Informatique',
            'Bande Dessinée',
            'Jeunesse',
            'Santé & Bien-être',
            'Art & Photographie',
            'Biographie',
            'Poésie',
            'Psychologie',
            'Religion & Spiritualité',
            'Sciences & Techniques',
            'Scolaire & Parascolaire',
            'Sport & Loisirs',
            'Tourisme & Voyage',
            'Économie & Gestion',
            'Littérature Classique',
            'Thriller & Polar',
            'Fantasy & Fantastique',
            'Romance',
            'Mystère & Enquête',
            'Horreur',
            'Ésotérisme & Paranormal',
            'Humour',
            'Anthologie & Recueil',
            'Théâtre',
            'Essai',
            'Philosophie',
            'Sociologie',
            'Politique',
            'Histoire de l\'art',
            'Architecture',
            'Design & Mode',
            'Jardinage & Nature',
            'Bricolage & Décoration',
            'Jeux & Récréation',
            'Éducation & Pédagogie',
            'Langues & Linguistique',
            'Droit & Justice',
            'Éducation Civique',
            'Sécurité & Défense',
            'Astronomie & Cosmologie',
            'Biologie',
            'Chimie',
            'Géologie',
            'Mathématiques',
            'Informatique & Programmation',
            'Électronique',
            'Robotique',
            'Ingénierie',
            'Énergie',
            'Aéronautique',
            'Automobile',
            'Transport',
            'Navigation',
            'Marine',
            'Militaire',
            'Guerre & Conflits',
            'Espionnage',
            'Criminalité',
            'Justice',
            'Éducation Sexuelle',
            'Maternité & Paternité',
            'Vie Quotidienne',
            'Recettes de Cuisine',
            'Nutrition',
            'Alimentation',
            'Voyages',
            'Guide Touristique',
            'Culture Locale',
            'Folklore',
            'Mythologie',
            'Légendes',
            'Contes',
            'Fables',
            'Thérapies Alternatives',
            'Médecine Traditionnelle',
            'Soins Naturels',
            'Fitness',
            'Yoga',
            'Méditation',
            'Développement Spirituel',
            'Spiritualité Orientale',
            'Spiritualité Occidentale',
            'Astrologie',
            'Tarot',
            'Divination',
            'Graphologie',
            'Archéologie',
            'Paléontologie',
            'Ethnologie',
            'Anthropologie',
            'Linguistique',
            'Philologie',
            'Lexicographie',
            'Sémantique',
            'Pragmatique',
            'Retraite',
            'Immobilier',
            'Gestion Financière',
            'Investissement',
            'Bourse',
            'Finance Personnelle',
            'Marketing',
            'Vente',
            'Commerce International',
            'Leadership',
            'Ressources Humaines',
            'Logistique',
            'Qualité',
            'Innovation',
            'Entrepreneuriat',
            'Startup',
            'Management',
            'Stratégie',
            'Organisation',
            'Productivité',
            'Efficacité',
            'Time Management',
            'Intelligence Émotionnelle',
            'Communication',
            'Négociation',
            'Persuasion',
            'Influence',
            'Relation Client',
            'Service Client',
            'Assistance Technique',
            'Dépannage',
            'Maintenance',
            'Réparation',
            'Installation',
            'Configuration',
            'Personnalisation',
            'Personnalité',
            'Caractère',
            'Tempérament',
            'Émotion',
            'Sentiment',
            'Cœur',
            'Esprit',
            'Âme',
            'Corps',
            'Santé Mentale',
            'Thérapie',
            'Coaching',
            'Conseil',
            'Mentorat',
            'Éducation',
            'Apprentissage',
            'Formation',
            'Enseignement',
            'Pédagogie',
            'Didactique',
            'Pédagogie Active',
            'Pédagogie Positive',
            'Éducation Positive',
            'Discipline Positive',
        ];

        foreach ($categories as $name) {
            Category::updateOrCreate(
                ['name' => $name],
                [
                    'id' => fake()->uuid(),
                    'description' => fake()->optional()->sentence(),
                    'coverUrl' => fake()->optional()->imageUrl(),
                ]
            );
        }
    }
}
